export const colors = {
  white: "#ffffff",
  lightGray: "#F0F4F3",
  darkGray: "#555555",
  aqua: "#50C2C9",
  black: "black",
  Gainsboro: "#DFDFDF",
  faintGrey: "#ccc",
  dodgerBlue: "#2196F3",
  silver: "#C8C8C8",
  bluishTurquoise: "#7DC9CE",
  teal: "#2E8F95",
  powderBlue: "#F1FDFE",
  softMint: "#F0F4F3",
};
